# ----------------------------------------------
# UYGULAMA ADI
# ----------------------------------------------
#server.port=9090
server.port=${PORT:9090}
spring.application.name=auth-api

# ----------------------------------------------
# VERİTABANI AYARLARI (H2 - GEÇİCİ VERİTABANI)
# ----------------------------------------------
# Uygulama çalışsın diye H2 kullanıyoruz.
# Kapatıp açınca veriler silinir (Test için ideal)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true

# ----------------------------------------------
# VERİTABANI AYARLARI (POSTGRESQL - PROD)
# ----------------------------------------------
#spring.datasource.url=jdbc:postgresql://localhost:5432/otigo_db
#spring.datasource.username=postgres
#spring.datasource.password=12345
#spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------------
# VERİTABANI AYARLARI (NEON CLOUD POSTGRESQL - CANLI)
# ----------------------------------------------
# Yeni bulut veritabanımız! Artık veriler AWS Frankfurt sunucularında tutuluyor.
spring.datasource.url=jdbc:postgresql://ep-dry-band-ag1i8mtj-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
#spring.datasource.password=npg_7kveQACPXd5J
spring.datasource.password=npg_QhgVW8tZ1eFs
spring.datasource.driver-class-name=org.postgresql.Driver

# Kodundaki Entity'lere (User, Child vb.) bakıp tabloları otomatik oluştur
spring.jpa.hibernate.ddl-auto=update

# SQL sorgularını terminalde göster (Tablolar oluşurken görmek için)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#token yenilemek için deniyorum
logging.level.org.springframework.mail=DEBUG


# ----------------------------------------------
# E-POSTA AYARLARI (GERÇEK GMAIL AYARLARI)
# ----------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=laraminakaradenizz@gmail.com
#spring.mail.password=akey hfin gnan ikbt
spring.mail.password=qriq svtx nfdo bejd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# ----------------------------------------------
# JWT AYARLARI
# ----------------------------------------------
application.security.jwt.secret-key=3afdb68aae5b6388e5845b58159dab833dd5bd6bc24f61fcacbdcf52dd850d5e4063714f31430cc53f9c7534f531e611f87ba815190bfb6d476785f5fd530122
application.security.jwt.expiration-ms=86400000
application.security.jwt.refresh-token.expiration-ms=604800000